### ISSUE TITLE
[Bug Report] Out of bounds progress bar

### ISSUE THREAD

**Issue by LowkeyCoding** [dr-nyt/NovelScraper#21]
**Please complete the following information):**
 - Operating System [OS]: Windows 10
 - App Version: 0.9.2

**Describe the bug**
Download progress bar is going out of bounds

**To Reproduce**
It happened when i tried to download this novel https://boxnovel.com/novel/versatile-mage/

**Expected behavior**
I expected it to be with in the box.

**Screenshots**
![image](https://user-images.githubusercontent.com/10528522/69981770-44cca880-1533-11ea-8720-32d1f43a8d4c.png)

**Comment by dr-nyt** [comment]
@LowkeyCoding thanks for bringing this to my attention. There seems to be a problem with the percentage calculation of how much the bar should be filled. It goes over 100% probably because my math is weak. I will hopefully have it fixed by the next update, but the good news is that your novel will download/update correctly. If it for some reason doesnt then get back to me and i will move it higher up on priority list.

PS, Just a dev tip, you can press ctrl+shift+i to open the console, and this will show you what the program is doing.

**Comment by dr-nyt** [comment]
This issue was fixed on the latest version.
